# -*- coding: utf-8 -*-
"""netflix cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nM0bEQTYu6t-nO6TP0WhBPmpc33F-0Cl
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/netflix-rotten-tomatoes-metacritic-imdb.csv", encoding = "unicode_escape")

df.info()

df.info()

df.head()

df.drop(["Image", "Poster", "TMDb Trailer", "Trailer Site", "IMDb Link", "Netflix Link", "Summary"], axis = 1, inplace = True)

df.info()

df.drop(["Rotten Tomatoes Score", "Metacritic Score", "Awards Received", "Awards Nominated For", "Boxoffice", "View Rating","Director", "Boxoffice", "Production House" ], axis = 1, inplace = True)

df.info()

df.dropna(inplace = True)

df.info()

df.describe()